#include <string>
#include <unordered_map>
#include "options.h"
#include "piece.h"

int MAX_THINKING_TIME_MS = 15000;
int MIN_THINKING_TIME_MS = 5;
int TIME_DIVISOR = 25;

int NODE_TM_BASE = 152;
int NODE_TM_SCALE = 120;
int NODE_TM_MIN = 60;
int NODE_TM_MAX = 140;

int INC_FRACTION = 75;
int HARD_LIMIT_MULTIPLIER = 250;
int INSTABILITY_DIVISOR = 5;
int MAX_INSTABILITY_FACTOR = 150;
int STABILITY_DECREMENT = 2;
int MAX_STABILITY_STEPS = 5;
int MIN_TIME_FACTOR = 40;
int SOFT_TO_HARD_MULTIPLIER = 2;

int GEN_AGE_WEIGHT = 8;

int MIN_LAR_INDEX = 4;
int MIN_LAR_DEPTH_REMAINING = 3;
int LAR_REDUCTION_DIVISOR = 7;

int MAX_HISTORY_EXTENSION = 1;
int HISTORY_EXTENSION_THRESHOLD = 3;

int MAX_HISTORY_EXTENSIONS_PER_LINE = 3;

int PV_DEPTH_ADDITION = 1;

int MAX_HEURISTIC_VALUE = 16384;

int HISTORY_REDUCTION_DIVISOR = 4000;
int CONTINUATION_REDUCTION_DIVISOR = 3000;
int CAPTURE_REDUCTION_DIVISOR = 3000;
int HEURISTIC_REDUCTION_THRESHOLD = 20;

int CAPTURE_HISTORY_SEE_SCORE_DIVISOR = 16;

int CORR_WEIGHT = 8;
int CORR_GRAIN = 256;
int CORR_MAX = 16384;

int BASE_LAP_INDEX = 3;
int MAX_LAP_DEPTH_REMAINING = 2;

int ASPIRATION_WINDOW = 35;

int MAX_QUIESCENCE_DEPTH = 30;
int MAX_QUIET_QUIESCENCE_CHECK_DEPTH = 2;

int MAX_RFP_DEPTH_REMAINING = 3;
int RFP_MARGIN_MULTIPLIER = 150;

int MAX_FP_DEPTH_REMAINING = 1;
int FP_MARGIN_MULTIPLIER = 150;

int MAX_RAZOR_DEPTH_REMAINING = 3;
int RAZOR_MARGIN = 300;

int MIN_NULL_PRUNING_DEPTH_REMAINING = 3;
int BASE_NULL_PRUNING_VERIFICATION_REDUCTION = 3;
int NULL_PRUNING_VERIFICATION_REDUCTION_DIVISOR = 6;

int MIN_SE_DEPTH_REMAINING = 6;
int SE_DEPTH_REMAINING_MIN_REDUCTION = 3;
int SE_MARGIN_MULTIPLIER = 2;
int SE_REDUCTION_BASE = 1;
int SE_REUCTION_DIVISOR = 2;
int SE_DOUBLE_EXTENSION_MARGIN = 300;

int MIN_IID_DEPTH_REMAINING = 6;
int IID_DEPTH_REDUCTION = 3;

int MIN_CHECK_EXTENSION_DEPTH_REMAINING = 2;
int MAX_CHECK_EXTENSIONS = 2;

int PIECE_VALUES[PIECE_NB] = { 100, 320, 330, 500, 975, 20000 };

std::unordered_map<std::string, int*> option_map =
{
	{"MAX_THINKING_TIME_MS", &MAX_THINKING_TIME_MS},
	{"MIN_THINKING_TIME_MS", &MIN_THINKING_TIME_MS},
	{"TIME_DIVISOR", &TIME_DIVISOR},

	{"NODE_TM_BASE", &NODE_TM_BASE},
	{"NODE_TM_SCALE", &NODE_TM_SCALE},
	{"NODE_TM_MIN", &NODE_TM_MIN},
	{"NODE_TM_MAX", &NODE_TM_MAX},

	{"INC_FRACTION", &INC_FRACTION},
	{"HARD_LIMIT_MULTIPLIER", &HARD_LIMIT_MULTIPLIER},
	{"INSTABILITY_DIVISOR", &INSTABILITY_DIVISOR},
	{"MAX_INSTABILITY_FACTOR", &MAX_INSTABILITY_FACTOR},
	{"STABILITY_DECREMENT", &STABILITY_DECREMENT},
	{"MAX_STABILITY_STEPS", &MAX_STABILITY_STEPS},
	{"MIN_TIME_FACTOR", &MIN_TIME_FACTOR},
	{"SOFT_TO_HARD_MULTIPLIER", &SOFT_TO_HARD_MULTIPLIER},

	{"GEN_AGE_WEIGHT", &GEN_AGE_WEIGHT},

	{"MIN_LAR_INDEX", &MIN_LAR_INDEX},
	{"MIN_LAR_DEPTH_REMAINING", &MIN_LAR_DEPTH_REMAINING},
	{"LAR_REDUCTION_DIVISOR", &LAR_REDUCTION_DIVISOR},

	{"MAX_HISTORY_EXTENSION", &MAX_HISTORY_EXTENSION},
	{"HISTORY_EXTENSION_THRESHOLD", &HISTORY_EXTENSION_THRESHOLD},

	{"MAX_HISTORY_EXTENSIONS_PER_LINE", &MAX_HISTORY_EXTENSIONS_PER_LINE},

	{"PV_DEPTH_ADDITION", &PV_DEPTH_ADDITION},

	{"MAX_HEURISTIC_VALUE", &MAX_HEURISTIC_VALUE},
	{"HISTORY_REDUCTION_DIVISOR", &HISTORY_REDUCTION_DIVISOR},
	{"CONTINUATION_REDUCTION_DIVISOR", &CONTINUATION_REDUCTION_DIVISOR},
	{"CAPTURE_REDUCTION_DIVISOR", &CAPTURE_REDUCTION_DIVISOR},
	{"HEURISTIC_REDUCTION_THRESHOLD", &HEURISTIC_REDUCTION_THRESHOLD},

	{"CAPTURE_HISTORY_SEE_SCORE_DIVISOR", &CAPTURE_HISTORY_SEE_SCORE_DIVISOR},

	{"CORR_WEIGHT", &CORR_WEIGHT},
	{"CORR_GRAIN", &CORR_GRAIN},
	{"CORR_MAX", &CORR_MAX},

	{"BASE_LAP_INDEX", &BASE_LAP_INDEX},
	{"MAX_LAP_DEPTH_REMAINING", &MAX_LAP_DEPTH_REMAINING},

	{"ASPIRATION_WINDOW", &ASPIRATION_WINDOW},

	{"MAX_QUIESCENCE_DEPTH", &MAX_QUIESCENCE_DEPTH},
	{"MAX_QUIET_QUIESCENCE_CHECK_DEPTH", &MAX_QUIET_QUIESCENCE_CHECK_DEPTH},

	{"MAX_RFP_DEPTH_REMAINING", &MAX_RFP_DEPTH_REMAINING},
	{"RFP_MARGIN_MULTIPLIER", &RFP_MARGIN_MULTIPLIER},

	{"MAX_FP_DEPTH_REMAINING", &MAX_FP_DEPTH_REMAINING},
	{"FP_MARGIN_MULTIPLIER", &FP_MARGIN_MULTIPLIER},

	{"MAX_RAZOR_DEPTH_REMAINING", &MAX_RAZOR_DEPTH_REMAINING},
	{"RAZOR_MARGIN", &RAZOR_MARGIN},

	{"MIN_NULL_PRUNING_DEPTH_REMAINING", &MIN_NULL_PRUNING_DEPTH_REMAINING},
	{"BASE_NULL_PRUNING_VERIFICATION_REDUCTION", &BASE_NULL_PRUNING_VERIFICATION_REDUCTION},
	{"NULL_PRUNING_VERIFICATION_REDUCTION_DIVISOR", &NULL_PRUNING_VERIFICATION_REDUCTION_DIVISOR},

	{"MIN_SE_DEPTH_REMAINING", &MIN_SE_DEPTH_REMAINING},
	{"SE_DEPTH_REMAINING_MIN_REDUCTION", &SE_DEPTH_REMAINING_MIN_REDUCTION},
	{"SE_MARGIN_MULTIPLIER", &SE_MARGIN_MULTIPLIER},
	{"SE_REDUCTION_BASE", &SE_REDUCTION_BASE},
	{"SE_REUCTION_DIVISOR", &SE_REUCTION_DIVISOR},
	{"SE_DOUBLE_EXTENSION_MARGIN", &SE_DOUBLE_EXTENSION_MARGIN},

	{"MIN_IID_DEPTH_REMAINING", &MIN_IID_DEPTH_REMAINING},
	{"IID_DEPTH_REDUCTION", &IID_DEPTH_REDUCTION},

	{"MIN_CHECK_EXTENSION_DEPTH_REMAINING", &MIN_CHECK_EXTENSION_DEPTH_REMAINING},
	{"MAX_CHECK_EXTENSIONS", &MAX_CHECK_EXTENSIONS},
};