#include <string>
#include <unordered_map>
#include "options.h"
#include "piece.h"

int MAX_THINKING_TIME_MS = 15000;
int MIN_THINKING_TIME_MS = 5;
int TIME_DIVISOR = 30;

int MIN_LAR_INDEX = 4;
int MIN_LAR_DEPTH_REMAINING = 3;
int LAR_REDUCTION_DIVISOR = 7;

int MAX_HEURISTIC_VALUE = 16384;

int HISTORY_REDUCTION_DIVISOR = 4000;
int CONTINUATION_REDUCTION_DIVISOR = 3000;
int HEURISTIC_REDUCTION_THRESHOLD = 20;

int BASE_LAP_INDEX = 3;
int MAX_LAP_DEPTH_REMAINING = 2;

int ASPIRATION_WINDOW = 35;

int MAX_QUIESCENCE_DEPTH = 30;
int MAX_QUIET_QUIESCENCE_CHECK_DEPTH = 2;

int MAX_RFP_DEPTH_REMAINING = 3;
int RFP_MARGIN_MULTIPLIER = 150;

int MAX_FP_DEPTH_REMAINING = 1;
int FP_MARGIN_MULTIPLIER = 150;

int MIN_NULL_PRUNING_DEPTH_REMAINING = 3;
int BASE_NULL_PRUNING_VERIFICATION_REDUCTION = 3;
int NULL_PRUNING_VERIFICATION_REDUCTION_DIVISOR = 6;

int MIN_SE_DEPTH_REMAINING = 8;
int SE_DEPTH_REMAINING_MIN_REDUCTION = 3;
int SE_MARGIN_MULTIPLIER = 2;
int SE_REDUCTION_BASE = 1;
int SE_REUCTION_DIVISOR = 2;

int RAZOR_MAX_DEPTH_REMAINING = 3;
int RAZOR_MARGIN = 300;

int MIN_IID_DEPTH_REMAINING = 6;
int IID_DEPTH_REDUCTION = 3;

int MIN_CHECK_EXTENSION_DEPTH_REMAINING = 2;
int MAX_CHECK_EXTENSIONS = 2;

int PIECE_VALUES[PIECE_NB] = { 100, 320, 330, 500, 975, 20000 };

std::unordered_map<std::string, int*> option_map =
{
	{"MAX_THINKING_TIME_MS", &MAX_THINKING_TIME_MS},
	{"MIN_THINKING_TIME_MS", &MIN_THINKING_TIME_MS},
	{"TIME_DIVISOR", &TIME_DIVISOR},

	{"MIN_LAR_INDEX", &MIN_LAR_INDEX},
	{"MIN_LAR_DEPTH_REMAINING", &MIN_LAR_DEPTH_REMAINING},
	{"LAR_REDUCTION_DIVISOR", &LAR_REDUCTION_DIVISOR},

	{"MAX_HEURISTIC_VALUE", &MAX_HEURISTIC_VALUE},
	{"HISTORY_REDUCTION_DIVISOR", &HISTORY_REDUCTION_DIVISOR},

	{"BASE_LAP_INDEX", &BASE_LAP_INDEX},
	{"MAX_LAP_DEPTH_REMAINING", &MAX_LAP_DEPTH_REMAINING},

	{"ASPIRATION_WINDOW", &ASPIRATION_WINDOW},

	{"MAX_RFP_DEPTH_REMAINING", &MAX_RFP_DEPTH_REMAINING},
	{"RFP_MARGIN_MULTIPLIER", &RFP_MARGIN_MULTIPLIER},

	{"MAX_FP_DEPTH_REMAINING", &MAX_FP_DEPTH_REMAINING},
	{"FP_MARGIN_MULTIPLIER", &FP_MARGIN_MULTIPLIER},

	{"MIN_NULL_PRUNING_DEPTH_REMAINING", &MIN_NULL_PRUNING_DEPTH_REMAINING},
	{"BASE_NULL_PRUNING_VERIFICATION_REDUCTION", &BASE_NULL_PRUNING_VERIFICATION_REDUCTION},
	{"NULL_PRUNING_VERIFICATION_REDUCTION_DIVISOR", &NULL_PRUNING_VERIFICATION_REDUCTION_DIVISOR},

	{"MIN_IID_DEPTH_REMAINING", &MIN_IID_DEPTH_REMAINING},
	{"IID_DEPTH_REDUCTION", &IID_DEPTH_REDUCTION},

	{"MIN_CHECK_EXTENSION_DEPTH_REMAINING", &MIN_CHECK_EXTENSION_DEPTH_REMAINING},
	{"MAX_CHECK_EXTENSIONS", &MAX_CHECK_EXTENSIONS},

	{"RAZOR_MAX_DEPTH_REMAINING", &RAZOR_MAX_DEPTH_REMAINING},
	{"RAZOR_MARGIN", &RAZOR_MARGIN},
};