#include <string>
#include <unordered_map>
#include "options.h"

int MAX_THINKING_TIME_MS = 20000;
int MIN_THINKING_TIME_MS = 150;
int TIME_DIVISOR = 25;
int DEPTH_TIME_CUTOFF_PERCENT = 60;

int MIN_LAR_INDEX = 6;
int MIN_LAR_DEPTH_REMAINING = 3;
int LAR_REDUCTION_DIVISOR = 7;

int MAX_HEURISTIC_VALUE = 16384;

int BASE_LAP_INDEX = 3;
int MAX_LAP_DEPTH_REMAINING = 2;

int ASPIRATION_WINDOW = 35;

int DELTA_PRUNING_MARGIN = 300;

int MAX_RFP_DEPTH_REMAINING = 4;
int RFP_MARGIN_MULTIPLIER = 150;

int MAX_FP_DEPTH_REMAINING = 2;
int FP_MARGIN_MULTIPLIER = 150;

int MIN_NULL_PRUNING_DEPTH_REMAINING = 3;
int BASE_NULL_PRUNING_VERIFICATION_REDUCTION = 3;
int NULL_PRUNING_VERIFICATION_REDUCTION_DIVISOR = 6;

int MIN_IID_DEPTH_REMAINING = 5;
int IID_DEPTH_REDUCTION = 3;

int MIN_CHECK_EXTENSION_DEPTH_REMAINING = 1;
int MAX_CHECK_EXTENSIONS = 2;

int PIECE_VALUES[6] = { 100, 320, 330, 500, 975, 20000 };

std::unordered_map<std::string, int*> option_map =
{
    {"MAX_THINKING_TIME_MS", &MAX_THINKING_TIME_MS},
    {"MIN_THINKING_TIME_MS", &MIN_THINKING_TIME_MS},
    {"TIME_DIVISOR", &TIME_DIVISOR},
    {"DEPTH_TIME_CUTOFF_PERCENT", &DEPTH_TIME_CUTOFF_PERCENT},

    {"MIN_LAR_INDEX", &MIN_LAR_INDEX},
    {"MIN_LAR_DEPTH_REMAINING", &MIN_LAR_DEPTH_REMAINING},
    {"LAR_REDUCTION_DIVISOR", &LAR_REDUCTION_DIVISOR},

    {"MAX_HEURISTIC_VALUE", &MAX_HEURISTIC_VALUE},

    {"BASE_LAP_INDEX", &BASE_LAP_INDEX},
    {"MAX_LAP_DEPTH_REMAINING", &MAX_LAP_DEPTH_REMAINING},

    {"ASPIRATION_WINDOW", &ASPIRATION_WINDOW},

    {"DELTA_PRUNING_MARGIN", &DELTA_PRUNING_MARGIN},

    {"MAX_RFP_DEPTH_REMAINING", &MAX_RFP_DEPTH_REMAINING},
    {"RFP_MARGIN_MULTIPLIER", &RFP_MARGIN_MULTIPLIER},

    {"MAX_FP_DEPTH_REMAINING", &MAX_FP_DEPTH_REMAINING},
    {"FP_MARGIN_MULTIPLIER", &FP_MARGIN_MULTIPLIER},

    {"MIN_NULL_PRUNING_DEPTH_REMAINING", &MIN_NULL_PRUNING_DEPTH_REMAINING},
    {"BASE_NULL_PRUNING_VERIFICATION_REDUCTION", &BASE_NULL_PRUNING_VERIFICATION_REDUCTION},
    {"NULL_PRUNING_VERIFICATION_REDUCTION_DIVISOR", &NULL_PRUNING_VERIFICATION_REDUCTION_DIVISOR},

    {"MIN_IID_DEPTH_REMAINING", &MIN_IID_DEPTH_REMAINING},
    {"IID_DEPTH_REDUCTION", &IID_DEPTH_REDUCTION},

    {"MIN_CHECK_EXTENSION_DEPTH_REMAINING", &MIN_CHECK_EXTENSION_DEPTH_REMAINING},
    {"MAX_CHECK_EXTENSIONS", &MAX_CHECK_EXTENSIONS},
};